/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import java.awt.BorderLayout;
import java.awt.Graphics;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;

import javax.swing.SwingUtilities;

import model.Point;

/**
 *
 * @author aliha
 */
public class TSPGraph extends javax.swing.JPanel {

     public ArrayList<Integer> tour;
    //private Timer timer;

    public TSPGraph() {
    }
     
    public TSPGraph(ArrayList<Integer> tour) {
        this.tour = tour;
        //timer = new Timer(5,this);
        //timer.start();
    }
    public void setNewTour(ArrayList<Integer> initialTour){
        tour = initialTour;
        repaint();
    }

    @Override
    public void paint(Graphics g) {
        super.paintComponent(g); //To change body of generated methods, choose Tools | Templates.
        
        
        if (tour != null) {
            ArrayList<Point> points = new ArrayList<>();
            tour.add(tour.get(0));
            int numberOfPoints = tour.size() - 1;
            int n = 300, x, y;
            for (int i = 0; i < numberOfPoints; i++) {
                x = (getWidth() / 2) + (int) (n * Math.cos(2 * i * (Math.PI / numberOfPoints)));
                y = (getHeight() / 2) - (int) (n * Math.sin(2 * i * (Math.PI / numberOfPoints)));
                points.add(new Point(x, y, i));
                g.fillOval(x - 7, y - 7, 15, 15);
                g.drawString(i + "", x + 10, y + 10);
            }
            for (int i = 0; i < tour.size() - 1; i++) {
				if (tour.get(i) != null && tour.get(i + 1) != null) {
					Point city1 = points.get(tour.get(i));
					Point city2 = points.get(tour.get(i + 1));
					g.drawLine((int) city1.getX(), (int) city1.getY(), (int) city2.getX(), (int) city2.getY());
				}
            }
        }
        
    
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 394, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 294, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents



    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
